<?php
return [
	//'/press/<url_slug:.*>/<prod_id:.*>'=>'/press-releases/press-report',0
	//'/press/<prod_id:.*>'=>'/press-releases/press-report',
	'/'=>'site/index',		
	'market-research/<curl:.*>'=>'reports/marketreport',
	'Report/<inc_id:.*>/<curl:.*>/<seg:.*>'=>'reports/reportsegment',
	'Report/<inc_id:.*>/<curl:.*>'=>'reports/report',	
	'Research/<inc_id:.*>/<curl:.*>/<seg:.*>'=>'reports/researchsegment',
	'Research/<curl:.*>-<inc_id:.*>/<seg:.*>'=>'reports/reportsegment',	
	'Research/<inc_id:.*>/<curl:.*>'=>'reports/researchsegment',					
	'Research/<curl:.*>-<inc_id:.*>'=>'reports/research',
	'inquiry-before-buying.php'=>'reports/inquiry',
	'pdfdownload.php'=>'reports/sample-request',
	'analystcall.php'=>'reports/analyst-query',
	'support.php'=>'reports/sales-query',
	'Domain/<cat:.*>/<curl:.*>'=>'reports/category-wise-report',
	'Domain/<subcat:.*>/<curl:.*>'=>'reports/category-wise-report',
	'press-releases.php'=>'press-releases/list-press',
	'PressRelease/<prod_id:.*>/<seo_keyword:.*>'=>'press-releases/press-report',
	//'pdfdownloadthankyou.php?id=<id:.*>'=>'message/thanks',                 
	'share-requirement.php'=>'reports/share-requirement',
	'contact-us.php'=>'home/contact-us',
	'Article/<custid:.*>/<seo_keyword:.*>'=>'news-article/article',
	'article.php'=>'news-article/list-article',
	'market-research-methodology.php'=>'reports/research-methodology',
	'team.php'=>'site/team',
	'about-us.php'=>'site/about',
	'privacy-policy.php'=>'home/privacy',
	'term-and-conditions.php'=>'home/terms',
	'career.php'=>'site/career',
	'Webinar/<inc_id:.*>/<curl:.*>'=>'webinar/webinar-detail',
	'WhitePaper/<prod_id:.*>/<seo_keyword:.*>'=>'whitepaper/whitepaper-detail',
	'WhitePaperDownload/<prod_id:.*>/<seo_keyword:.*>'=>'whitepaper/whitepaper-download',
	'login.php'=>'site/login',
	//'registration.php'=>'site/registration',
	'purchasereport.php'=>'purchase/buy-report',
	'sitemap.html'=>'sitemap/sitemap-html',
	//'quotation.php'=>'reports/request-quote',
	'createsitemap'=>'sitemap/create-sitemap-xml',
	'packagepage.php'=>'home/new-package',
	'newcheckout.php'=>'home/new-checkout',
	'thank-you.php' => 'purchase/thank-you',
	'payment-failed.php' => 'purchase/payment-failed'

	//'/category/<slug:.*>.html'=>'/finder/category',
];