 <?php
 use yii\helpers\Url;
 ?>
<div class="row child-nav">
    <div class="breadcrumb col-8 ">
      <ul>
       <li><a href="<?= Url::to(['site/index']); ?>">Home</a></li>
        <li>Terms and Conditions</li>
      </ul>
    </div>
  </div>
<div class="main-content articles">
  <div class="content-area">
    <div class="white-papers-main">
      <h1 class="text-center"><span class="title-brdr">Terms and Conditions</span></h1>
      <div class="row">
      <div class="content-column-full"><div class="basic-content">
      <p><b>Delivery of Report:</b></p>
<div align="">
  <ul>
    <li>In   case of online download, the report will be delivered to you by email   within 48 hours of receipt of payment. However, in case of physical   delivery of the print copy of the report the client will be charged   separately. We will courier the report within 3 to 5 working days from   the date of the receipt of payment, depending on the location of the   user.</li>
    <li>All   our customers are entitled to receive a 20% free customization in the   report based on their specific requirements pertaining to the markets   discussed in the report, once the report is purchased. However,   complexity of your requirement and time taken will be purely judged by   our analyst and IndustryARC will have the final say regarding the same.</li>
  </ul>
</div>
<p align="justify"><strong>Cancellation Policy:</strong></p>
<div align="justify">
  <ul>
    <li>Kindly   read all the information about the report before placing your order.   Cancellation of orders will not be accepted after the payment has been   made and the report has been dispatched.</li>
    <li>Due   to the confidential nature of the information contained in our market   research reports,cancellation of orders cannot be accepted after the   report has been delivered.</li>
    <li>However,   in the case of missing or incomplete data in our market research   report, IndustryARC will provide the data as soon as possible as part of   the original report.</li>
  </ul>
</div>
<p align="justify"> </p>
<div align="justify">This content is an   electronic record in terms of Information Technology Act 2000 and rules   there under as applicable and the amended provisions pertaining to   electronic records in various statutes as amended by the Information   Technology Act 2000. This electronic record is generated by a computer   system and does not require any physical or digital signatures.<br />
  <br />
  This   content is published in accordance with the provisions of Rule 3(1) of   the Information Technology (Intermediaries guidelines) Rules, 2011 that   require publishing the rules and regulations, privacy policy and Terms   of Use or usage of industryarc.com<br />
  <br />
  <strong>1.   Acceptance:</strong><br />
  <br />
  The domain name IndustryARC (hereinafter referred to as &ldquo;<a target="" title="" href="https://www.industryarc.com">Industryarc.com</a>&rdquo;)   is owned by Furion Analytics Research &amp; Consulting LLP a company   incorporated under the Companies Act, 2013 with its registered office at   Flat # 202, H.No. 1-89/2/1, 2nd Fl, Lotus Pond Apt, Gafoor Nagar, Near   Durgam Cheruvu, Madhapur, Hyderabad - 500081, Telangana, INDIA   (hereinafter referred to as &ldquo;IndustryARC&rdquo;).<br />
  <br />
  <strong>2.  Membership Eligibility:</strong><br />
  <br />
  Use   of the website is available only to persons who can form legally   binding contracts under the Indian Contract Act, 1872. Persons who are   &ldquo;incompetent to contract&rdquo; within the meaning of the Indian Contract Act   1872, including minors, un-discharged insolvents etc are not eligible to   use the Website. If you are a minor i.e. under the age of 18 years, you   shall not register as a User of IndustryARC website and shall not   transact on or use the website. As a minor if you wish to transact on   the website, such use or transaction maybe made by your legal guardian   or parents on the Website. IndustryARC reserves the right to terminate   your membership and/or refuse to provide you with access to the website   if it is brought to the notice of IndustryARC or if it is discovered   that you are under the age of 18 years or are otherwise incompetent to   contract.<br />
  <br />
  <strong>3.  License:</strong><br />
  <br />
  IndustryARC   grants you a limited, non-exclusive, non-transferable, non-assignable,   revocable license to view and temporarily download a copy of the   materials displayed on the Site solely for your personal and   non-commercial use or for your organization's legitimate business use.   All materials displayed or made available on the Site, including, but   not limited to, graphics, documents, text, images, sound, video, audio,   artwork, software, and HTML code (collectively, the &quot;Material&quot; or   &quot;Materials&quot;) are the exclusive property of IndustryARC or its content   suppliers. The Materials are protected by Indian and international   copyright laws and any other applicable intellectual property rules,   regulations, and laws. Except as expressly permitted herein, you shall   not (i) use, copy, modify, display, delete, distribute, download, store,   reproduce, transmit, publish, sell, re-sell, adapt, reverse engineer,   or create derivative works of the Material, or (ii) use the Material on   any other web sites or any media, e.g., networking environment, without   IndustryARC&rsquo;s prior written consent.<br />
  <br />
  All   trademarks, service marks, and logos (the &quot;Marks&quot;) displayed on the   Site are the exclusive property of IndustryARC and/or their respective   owners. You shall not use the Marks in any manner without IndustryARC&rsquo;s   and/or their respective owners' prior written consent.<br />
  <br />
  <strong>4. User Submissions:</strong><br />
  <br />
  The   Site provides a forum for you to obtain information from and about   IndustryARC. By submitting or entering any information to the Site   (&quot;Submitted Information&quot;), you agree that you grant IndustryARC a   perpetual, non-exclusive, irrevocable, royalty free, worldwide license   and right, but not the obligation, to use, copy, modify, display,   distribute, download, store, reproduce, transmit, publish, transfer,   adapt, create derivative works in any manner, in their entirety or a   portion of, your Submitted Information, and by any means, forever and   worldwide.<br />
  <br />
  You acknowledge and agree   that IndustryARC may retain copies of your Submitted Information and   disclose your Submitted Information to a third party if IndustryARC   believes that it is necessary to: (i) protect the integrity of the Site;   (ii) protect the rights of IndustryARC; (iii) comply with any court   order; (iv) comply with any legal proceedings; (v) assert IndustryARC's   claim under this Notice; and (vi) satisfy any claims regarding   violations of third party's rights. <br />
  Furthermore,   you acknowledge and agree that IndustryARC may use your Submitted   Information for training, data aggregation and other internal purposes.<br />
  <br />
  <br />
  <strong>5.  Disclaimer:</strong><br />
  <br />
  You   acknowledge and accept that: (i) you assume all risks related to or   resulting from your usage, viewing, or access of the site and its   materials. The site and its materials are provided on an &quot;as is&quot; and an   &quot;as available&quot; basis. (ii) IndustryARC expressly disclaims all   warranties of any kind, either express or implied, including, but not   limited to, the implied warranties of merchantability, fitness for a   particular purpose, non-infringement, or warranties arising from course   of performance, course of dealing or usage. (iii) IndustryARC expressly   disclaims all warranties (a) that the site and its materials will be   error- free or virus- free ; (b) that the site will be uninterrupted and   secure; (c) that the site will meet your requirements; and (d)   regarding the reliability, accuracy, completeness, validity, timeliness   or truthfulness of any submitted information. Any materials downloaded   or otherwise obtained are done so at your own discretion and risk, and   you are solely responsible for any damage to your computer system or   loss of data that results from the download of any such materials.<br />
  <br />
  <br />
  <strong>6.  Liability and limitations of liability:</strong><br />
  <br />
  You   understand and agree that the site and its materials are not a   substitute for professional advice. you understand and agree that some   laws, regulations, guidelines and other matters addressed in the site   and its materials are subject to interpretation and that you shall be   solely responsible for, and waive any claim against IndustryARC, and   their respective affiliates, officers, agents, and employees for any   loss, damage and expense (or claim thereof) resulting from your use of   the site and its materials. You agree that the availability of the site   and its materials shall not be construed as the rendering of any tax,   legal, attest, accounting, auditing or other professional, services or   advice.<br />
  <br />
  You agree to assume all risks   associated with, arising out of, or resulting from your use of the site,   the materials, or any submitted information, including, but not limited   to, the risks of financial loss, physical harm, property damages,   dealing with other users of the site , strangers, minors, or foreign   nationals, and persons acting under false pretense.<br />
  <br />
  You   further agree to release IndustryARC and their respective affiliates,   officers, agents, and employees, harmless from all claims, demands,   damages (including without limitation direct, indirect, consequential,   incidental, special, or damages for loss of profits, goodwill, revenue,   data, or use, incurred by you or any third party, whether in an action   in contract, tort, or breach or failure of warranty, even if IndustryARC   has been advised of the possibility of such damages) of any kind or   nature, known or unknown, associated with, arising out of, or resulting   from your usage of the site, the materials, any submitted information,   and any transactions related to or resulting from your use of the site.<br />
  <br />
  <strong>7.  Termination:</strong><br />
  <br />
  IndustryARC   shall have the right, in its sole discretion, to terminate any services   of the Site and remove any Materials from the Site. IndustryARC may   also terminate your access to any part or all of the services provided   by IndustryARC on the Site at any time, with or without cause or notice,   for any or no reason. IndustryARC shall not be responsible for   maintaining or returning your Submitted Information.</div>
      </div></div>
      </div>
    </div>
  </div>
</div>
